### ISSUE TITLE
Core: Error handler (BE)

### ISSUE THREAD

**Issue by chequille** [TYPO3-extensions/news#68]
Hi,
I am using
Typo3 7.6.4
news 4.2.1
eventnews 1.1.0
Everything seems to work but I get a lot of messages in the protocoll like:
`Core: Error handler (BE): PHP Warning: Declaration of GeorgRinger\Eventnews\Hooks\BackendUtility::updateFlexforms(&$params, &$reference) should be compatible with GeorgRinger\News\Hooks\BackendUtility::updateFlexforms(array &$dataStructure, array $row) in /var/www/vhosts/......../typo3conf/ext/eventnews/Classes/Hooks/BackendUtility.php line 51 `

Do you know about this and is there already a fix for it?
Best regards,
Jürgen

**Comment by georgringer** [comment]
This is a warning and related to php7. I try to fix that soon

**Comment by chequille** [comment]
Hi Georg,
that's fine. Thanks for your reply.
Because I am getting this warnings as well from other extensions and because now I know it is coming from php 7, I am switching back to php 5.6 for the moment.
I guess php 7 is not giving better performance with Typo 7.6.5 and therfore it will be OK. But of course when using Typo 8 in the future it should be fixed.
Best regards,
Jürgen

**Comment by georgringer** [comment]
Fixed in master of eventnews

**Comment by Tonyt8** [comment]
Hi Georg,
I am using
Typo3 7.6.11
news 4.3.0
eventnews 1.1.0
php7.0.6

I hope it's okay jumping on the thread.
I am have a similar problem as chequille  had.
Yesterday I tried updating the "news" extension to 5.0.1
My news system failed after the update 5.0.1.
 I have a 2 language setup. The category menu would not work any more.
Other things seem to be odd. I tried fixing things, but made a mess of the complete website system.
Anyway I have totally installed the website and started again from the archive files.
The news is working perfect now (version 4.3.0.) I have installed the eventnews 1.1.0 again. I can make eventnews items without any issues. The error warning is shown when I add a page content news system plugin.
How can I fix the issue. I am unsure what you mean above "Fixed in master of eventnews". What is the master? I cannot find a master.
I don't want to risk adding the plugin until the error message is solved, I don't want to repeat the problems I faced yesterday,   

Many thanks in advance,
Kind regards,
Tony

The error message I receive:
PHP Warning
Core: Error handler (BE): PHP Warning: Declaration of GeorgRinger\Eventnews\Hooks\BackendUtility::updateFlexforms(&$params, &$reference) should be compatible with GeorgRinger\News\Hooks\BackendUtility::updateFlexforms(array &$dataStructure, array $row) in /kunden/112563_73765/rp-hosting/5005132/6005132/typo3cms/projt3_2pack/typo3conf/ext/eventnews/Classes/Hooks/BackendUtility.php line 0

**Comment by Tonyt8** [comment]
Hi,
Now I understand what Master is, but I don't find any recently update files there. I will try manually installing it.

Regards,
Tony

**Comment by Tonyt8** [comment]
Hi Georg,

I have now installed eventnews 1.1.1, cleared the install tool cache.
I still have this error:

PHP Warning
Core: Error handler (BE): PHP Warning: Declaration of GeorgRinger\Eventnews\Hooks\BackendUtility::updateFlexforms(&$params, &$reference) should be compatible with GeorgRinger\News\Hooks\BackendUtility::updateFlexforms(array &$dataStructure, array $row) in /kunden/112563_73765/rp-hosting/5005132/6005132/typo3cms/projt3_2pack/typo3conf/ext/eventnews/Classes/Hooks/BackendUtility.php line 0

Please can you advise / help?

Thanks.

Kind regards,
Tony

**Comment by georgringer** [comment]
https://github.com/georgringer/eventnews

**Comment by Tonyt8** [comment]
Thanks Georg

Regards,
Tony

**Comment by Lobster1956** [comment]
i have the same Warning with:
- PHP 7.0.14
- TYPO3 7.6.15
- news 5.3.2
- eventnews 1.2.0
Core: Error handler (FE): PHP Warning: Declaration of GeorgRinger\Eventnews\ViewHelpers\DayCompareViewHelper::render($newsItem, $demand) should be compatible with TYPO3\CMS\Fluid\Core\ViewHelper\AbstractConditionViewHelper::render() in ...  line 48

**Comment by abdel07** [comment]
I have the same warning
PHP 7.0.7
eventnews 1.2.0

PHP Warning: Declaration of GeorgRinger\Eventnews\ViewHelpers\DayCompareViewHelper::render($newsItem, $demand) should be compatible with TYPO3\CMS\Fluid\Core\ViewHelper\AbstractConditionViewHelper::render()
